language: java
jdk: oraclejdk8
install: mvn install
deploy:
   edge: true
   provider: cloudfoundry
   username: terentich@bk.ru
   password: 
     secure: "test"
   api: https://api.run.pivotal.io
   organization: terentich-org
   space: development