name: Package

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  package:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Package with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Create pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          automatic_release_tag: "latest"
          files: backend/target/*.jar